/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum2;

/**
 *
 * @author User
 */
public class ProgramAritmatika extends javax.swing.JFrame {
    String jns ="";
    int jml;
    public ProgramAritmatika() {
        initComponents();
        getjumlah();
        setjenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        operasi = new javax.swing.JLabel();
        ket = new javax.swing.JLabel();
        bil4 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        jmlbil = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        b4 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        jenis = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 255, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Jenis Aritmatika");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PROGRAM ARITMATIKA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 10, 170, 30);

        panel.setLayout(null);

        operasi.setText("Operasi");
        panel.add(operasi);
        operasi.setBounds(10, 0, 60, 20);

        ket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel.add(ket);
        ket.setBounds(100, 20, 140, 30);

        bil4.setText("Bilangan 4");
        panel.add(bil4);
        bil4.setBounds(30, 200, 80, 20);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil);
        pilihanbil.setBounds(140, 70, 150, 20);

        jmlbil.setText("Jumlah Bilangan");
        panel.add(jmlbil);
        jmlbil.setBounds(30, 70, 80, 20);

        bil1.setText("Bilangan 1");
        panel.add(bil1);
        bil1.setBounds(30, 110, 80, 20);

        bil2.setText("Bilangan 2");
        panel.add(bil2);
        bil2.setBounds(30, 140, 80, 20);

        bil3.setText("Bilangan 3");
        panel.add(bil3);
        bil3.setBounds(30, 170, 80, 20);

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        panel.add(b4);
        b4.setBounds(140, 190, 150, 30);

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        panel.add(b1);
        b1.setBounds(140, 100, 150, 30);

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        panel.add(b2);
        b2.setBounds(140, 130, 150, 30);

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        panel.add(b3);
        b3.setBounds(140, 160, 150, 30);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        panel.add(hitung);
        hitung.setBounds(180, 230, 90, 23);

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        panel.add(hasil);
        hasil.setBounds(140, 270, 160, 70);

        jPanel1.add(panel);
        panel.setBounds(40, 80, 330, 350);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jPanel1.add(jenis);
        jenis.setBounds(240, 40, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 440);

        setBounds(0, 0, 416, 478);
    }// </editor-fold>//GEN-END:initComponents

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        Double hsl = 0.0;
        Double a1,a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        a3 = Double.parseDouble(b3.getText().toString());
        a4 = Double.parseDouble(b4.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml ==2 ){
                hsl = a1 +a2;
                hasil.setText(""+a1+" + "+a2+" = "+hsl);
            }
            if (jml == 3 ){
                hsl = a1 +a2+ a3;
                hasil.setText(""+a1+" + "+a2+" + "+a3+" = "+hsl);
            }
            if(jml == 4 ){
                hsl = a1 +a2+ a3 + a4;
                hasil.setText(""+a1+" + "+a2+" + "+a3+" + "+a4+" = "+hsl);
            }
        }
        else if(jns.equals("Pengurangan")){
            if(jml ==2 ){
                hsl = a1 - a2;
                hasil.setText(""+a1+" - "+a2+" = "+hsl);
            }
            if(jml == 3 ){
                hsl = a1 - a2 - a3;
                hasil.setText(""+a1+" - "+a2+" - "+a3+" = "+hsl);
            }
            if(jml == 4 ){
                hsl = a1 - a2 - a3 - a4;
                hasil.setText(""+a1+" - "+a2+" - "+a3+" - "+a4+" = "+hsl);
            }
        }
        else if(jns.equals("Perkalian")){
            if(jml ==2 ){
                hsl = a1 * a2;
                hasil.setText(""+a1+" x "+a2+" = "+hsl);
            }
            if(jml == 3 ){
                hsl = a1 * a2 * a3;
                hasil.setText(""+a1+" x "+a2+" x "+a3+" = "+hsl);
            }
            if(jml == 4 ){
                hsl = a1 * a2 * a3 * a4;
                hasil.setText(""+a1+" x "+a2+" x "+a3+" x "+a4+" = "+hsl);
            }
        }
        else if(jns.equals("Pembagian")){
            if(jml ==2 ){
                hsl = a1 / a2;
                hasil.setText(""+a1+" : "+a2+" = "+hsl);
            }
            if(jml == 3 ){
                hsl = a1 / a2 / a3;
                hasil.setText(""+a1+" : "+a2+" : "+a3+" = "+hsl);
            }
            if(jml == 4 ){
                hsl = a1 / a2 / a3 / a4;
                hasil.setText(""+a1+" : "+a2+" : "+a3+" : "+a4+" = "+hsl);
            }
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
       setjenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        getjumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed
    public void getjumlah(){
    if(pilihanbil.getSelectedItem().equals("2")){
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        jml = 2;
    }else if(pilihanbil.getSelectedItem().equals("3")){
        bil3.setVisible(true);
        bil4.setVisible(false);
        b3.setVisible(true);
        b4.setVisible(false);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        jml = 3;
    }else if(pilihanbil.getSelectedItem().equals("4")){
        bil3.setVisible(true);
        bil4.setVisible(true);
        b3.setVisible(true);
        b4.setVisible(true);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        jml = 4;
    }
    }
    public void setjenis(){
    if(jenis.getSelectedItem().equals("Penjumlahan")){
        jns = "Penjumlahan";
        jmlbil.setText("Penjumlahan");
        panel.setVisible(true);
        pilihanbil.setEnabled(true);
        ket.setText("Penjumlahan");
    }
    else if (jenis.getSelectedItem().equals("Pengurangan")){
        jns = "Pengurangan";
        jmlbil.setText("Pengurangan");
        panel.setVisible(true);
        pilihanbil.setEnabled(true);
        ket.setText("Pengurangan");
    }
    else if (jenis.getSelectedItem().equals("Perkalian")){
        jns = "Perkalian";
        jmlbil.setText("Perkalian");
        panel.setVisible(true);
        pilihanbil.setEnabled(true);
        ket.setText("Perkalian");
    }
    else if(jenis.getSelectedItem().equals("Pembagian")){
        jns = "Pembagian";
        jmlbil.setText("Pembagian");
        panel.setVisible(true);
        pilihanbil.setEnabled(true);
        ket.setText("Pembagian");
    }
    
    }
    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramAritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel jmlbil;
    private javax.swing.JLabel ket;
    private javax.swing.JLabel operasi;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    // End of variables declaration//GEN-END:variables

   
}
